config/routes.rb
Rails.application.routes.draw do
  root to: "channels#index"

  get 'sessions' => 'sessions#show'
  post 'sessions' => "sessions#create", as: :create_session


  get 'channels/:id' => 'channels#show', as: :channel
  # resources :channels


  post 'channel/:channel_id/messages' => 'messages#create', as: :create_message
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :messages
end

app/models/channel_membership.rb
class ChannelMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel

  # has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
  end

  def show
    @channel = Channel.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    channel = Channel.find(params[:channel_id])
    user = User.find(session[:user_id])

    channel.messages.create(user: user, content: params[:content])

    redirect_to channel_path(channel)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
  end

  def create
    session[:user_id] = params[:user_id]

    redirect_to root_path, notice: 'Your logged in'
    # redirect_to '/'
    # redirect_to [:session, ]
    # redirect_to user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channels/index.slim
h1 Channels

ul
  - Channel.all.each do |channel|
    li=link_to channel.name, channel_path(channel)
    / # li=link_to channel.name, "/channels/#{channel.id}"

app/views/channels/show.slim
h2= @channel.name

ul
  - @channel.messages.each do |msg|
    li
      strong> #{msg.user.try(:name)}:
      | #{msg.content}


= form_tag create_message_path(@channel), method: "POST" do
  input name="content" placeholder="message content"

  input type="submit" value="send"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if session[:user_id].present? %>
  <p>Logged in as: <%= User.find(session[:user_id]).name %></p>
<% end %>

<%= yield %>

</body>
</html>